{% set name = "opensarlab_lib" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ea2030e4802f731d832b16c0b409a9e4ac896d8cedd260bce1325971604f346

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8
    - asf_search
    - cartopy
    - gdal
    - hyp3_sdk
    - ipywidgets
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - shapely
    - pyshp

test:
  imports:
    - opensarlab_lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ASFOpenSARlab/opensarlab-lib
  summary: A Python library to support ASF OpenSARlab's Jupyter Notebook repository https://github.com/ASFOpenSARlab/opensarlab-notebooks
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Alex-Lewandowski
    - jhkennedy
    - dgpalmieri
